services:
  banking:
    image: somkiat/banking:1.0
    build:
      context: ./banking
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test@123
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: bankdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 5