apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdEAxMjM=  # Base64 for "test@123"
  SPRING_DATASOURCE_PASSWORD: dGVzdEAxMjM= # Base64 for "test@123"